### PR TITLE
Add service account email option

### PR DESCRIPTION
**Pull request by cisaacstern**
If `gcloud` login is a service account, the `service_account_email` needs to be passed explicitly in PipelineOptions.

This PR adds that option.

### CODE REVIEW

**Comment by yuvipanda** [comment]
@cisaacstern I want to try avoid setting this if possible, and have it be automatically figured out from the environment. Can you tell me what was the error you were getting?

**Comment by cisaacstern** [comment]
Yes setting it automatically somehow would be cleaner if possible.

Without this option, if I deploy to dataflow with `gcloud login` set to a service account, then the pipeline deploys, but it fails with

```
IOError("Forbidden: %s\n%s" % (path, msg)) OSError: Forbidden: https://storage.googleapis.com/download/storage/v1/b/pfcsb-bucket/o/gpcp-1661554877%2F.zgroup?alt=media 13667658525-compute@developer.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. [while running 'Start|cache_input|Reshuffle_000|prepare_target|Reshuffle_001|store_chunk|Reshuffle_002|finalize_target|Reshuffle_003/prepare_target-ptransform-56']
```

So it's using the default project service account `13667658525-compute@developer.gserviceaccount.com` for certain things that it should be using the user-specified service account for instead.

**Comment by cisaacstern** [comment]
@yuvipanda, actually I'd love to take a stab at setting the default for this based on

https://github.com/yuvipanda/pangeo-forge-runner/blob/956a970e14b60b071e60ab52faa7dd7e64485bef/pangeo_forge_runner/bakery/dataflow.py#L30-L40

I'll try that now!

**Comment by cisaacstern** [comment]
I think https://github.com/yuvipanda/pangeo-forge-runner/pull/15/commits/90ef1dabf61a07b855e3eec59c2270b90997f3f7 does what we want? This is indeed much simpler. 😄

**Comment by yuvipanda** [comment]
@cisaacstern yay thanks for sorting out the default. This LGTM - add a test and we'll merge?

**Comment by cisaacstern** [comment]
👋 @yuvipanda, IMHO this is ready to go.

Re: FileNotFoundError vs. ValueError, looks like that's just a difference between my local test env and GitHub Actions runner.

**Comment by yuvipanda** [comment]
@cisaacstern hmm, if i try this I get:

```
  "error": {
    "code": 400,
    "message": "(afc57fa6c1eea86e): Current user cannot act as service account yt2796@columbia.edu. Please grant your user account one of [Owner, Editor, Service Account Actor] roles, or any other role that includes the iam.serviceAccounts.actAs permission. See https://cloud.google.com/iam/docs/service-accounts-actas for additional details.",
    "status": "INVALID_ARGUMENT"
  }
}
```

while everything works fine without this PR.

Are you using a local service account to launch this? Where were you seeing the error you reported?

**Comment by cisaacstern** [comment]
Yes, I've been using a local service account, and if you do that, the reported error (which this fixes) comes up on Dataflow.

I think 6f330d5 should fix the problem you're seeing? Thanks for actually trying this out, great to catch this bug pre-merge. 🙏

**Comment by yuvipanda** [comment]
I left a comment about comments, happy to merge otherwise! The codecov failure is ok in this specific case because I don't wanna have to setup a harness that deletes the gcloud command...

**Comment by cisaacstern** [comment]
Docstring + comments are good now I think!

**Comment by yuvipanda** [comment]
Thanks @cisaacstern

**Pull request merged**
